### PR TITLE
add support for env-files

### PR DESCRIPTION
**Pull request by xmlking**
fix https://github.com/chihab/dotenv-run/issues/15

### CODE REVIEW

**Comment by chihab** [comment]
Thanks for the PR.
It would be cool if you could add some unit tests.

There is an issue in the pipeline which not related to your PR. I am on it.

**Comment by xmlking** [comment]
> Thanks for the PR. It would be cool if you could add some unit tests.
> 
> There is an issue in the pipeline which is not related to your PR. I am on it.

Sure , will add test cases

**Comment by xmlking** [comment]
I think we should process them in order.
E.g., 
```shell
dotenv-run -f .secrets -f extra  -- bash -c 'echo \"Hello World $API_USERS\"'"
```
Should process **.env** then **.secrets**  then **extra**

**Comment by xmlking** [comment]
added unit test   
image

**Comment by xmlking** [comment]
will you be releasing this PR ?

**Comment by chihab** [comment]
Been quite busy these day. I'll have a look at it asap.
Thanks @xmlking

**Comment by xmlking** [comment]
wonder  reason behind printing `/API/` environment variables in the console! 

https://github.com/chihab/dotenv-run/blob/bcd0dff2ecf5fe316ba6598d48dd94154bc5990b/packages/cli/src/index.mts#L43

**Comment by chihab** [comment]
No reason, this should be removed.
Thanks.

**Pull request merged**
